DROP DATABASE IF EXISTS VOYAGE;

CREATE DATABASE VOYAGE;
USE VOYAGE;

CREATE TABLE ville(
        ID_ville int Auto_increment NOT NULL PRIMARY KEY,
        nom_ville varchar(50)  NOT NULL,
        description varchar(200)  NOT NULL
);

CREATE TABLE point_interet(
        ID_pt_interet  Int Auto_increment NOT NULL PRIMARY KEY,
        nom_pt_interet varchar(50)  NOT NULL,
        epoque varchar(50)  NOT NULL,
        categorie varchar(50)  NOT NULL,
        description_pt_interet varchar(200)  NOT NULL,
        nom_architecte varchar(50)  NOT NULL,
        publier tinyint(1) NOT NULL,
        chemin_photo1 varchar(150)  NOT NULL,
        chemin_photo2 varchar(150)  NOT NULL,
        chemin_photo3 varchar(150)  NOT NULL,
        ID_ville int NOT NULL,
        CONSTRAINT fkVilleInteret FOREIGN KEY (ID_ville) REFERENCES ville(ID_ville)
);

CREATE TABLE utilisateur(
        ID_utilisateur int Auto_increment NOT NULL PRIMARY KEY,
        nom_utilisateur varchar(50)  NOT NULL,
        prenom varchar(50)  NOT NULL,
        pseudo varchar(50)  NOT NULL,
        mot_de_passe varchar(50)  NOT NULL,
        droit_acces int NOT NULL,
        activer tinyint(1) NOT NULL
);

CREATE TABLE avoir(
        ID_pt_interet int NOT NULL,
        ID_utilisateur int NOT NULL,
        CONSTRAINT fkInteretAvoir FOREIGN KEY (ID_pt_interet) REFERENCES point_interet(ID_pt_interet),
        CONSTRAINT fkUtilisateurAvoir FOREIGN KEY (ID_utilisateur) REFERENCES utilisateur(ID_utilisateur)
);


INSERT INTO `ville` (`ID_ville`,`nom_ville`,`description`) VALUES (null,"Phasellus","Cum sociis natoque penatibus et magnis dis parturient"),(null,"eu nibh","magnis dis parturient montes, nascetur"),(null,"sagittis. Duis","egestas. Aliquam nec enim. Nunc ut erat. Sed nunc"),(null,"vel,","dui, semper et, lacinia vitae, sodales at, velit. Pellentesque"),(null,"dolor,","velit. Pellentesque ultricies"),(null,"dictum cursus.","nec metus facilisis lorem tristique aliquet."),(null,"ac","consectetuer adipiscing elit. Curabitur sed tortor."),(null,"Aliquam","dictum magna."),(null,"Curabitur","felis eget varius ultrices, mauris"),(null,"sociis natoque","a");
INSERT INTO `ville` (`ID_ville`,`nom_ville`,`description`) VALUES (null,"auctor","odio semper cursus. Integer mollis. Integer tincidunt aliquam"),(null,"mollis vitae,","ac turpis egestas. Fusce aliquet"),(null,"arcu","diam at pretium aliquet, metus urna convallis erat, eget tincidunt"),(null,"vitae dolor.","erat, in consectetuer"),(null,"rutrum","erat. Sed nunc"),(null,"odio. Aliquam","pharetra ut, pharetra sed,"),(null,"dui","ac turpis egestas. Aliquam fringilla cursus purus. Nullam"),(null,"varius","diam luctus lobortis. Class aptent taciti sociosqu ad"),(null,"consectetuer mauris","felis orci, adipiscing non, luctus sit amet, faucibus"),(null,"odio. Aliquam","magna a neque. Nullam ut nisi");
INSERT INTO `ville` (`ID_ville`,`nom_ville`,`description`) VALUES (null,"massa","neque. In"),(null,"Maecenas libero","rutrum lorem ac risus. Morbi metus. Vivamus"),(null,"feugiat tellus","In lorem."),(null,"ligula.","Suspendisse non leo."),(null,"eu turpis.","et tristique pellentesque, tellus sem"),(null,"at","mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida"),(null,"enim","Vivamus euismod"),(null,"et risus.","nulla magna, malesuada vel, convallis"),(null,"eu","ornare, elit"),(null,"per","Morbi");
INSERT INTO `ville` (`ID_ville`,`nom_ville`,`description`) VALUES (null,"elit. Aliquam","ut aliquam iaculis, lacus pede sagittis"),(null,"arcu","fringilla. Donec feugiat metus sit amet ante. Vivamus non"),(null,"lobortis. Class","massa rutrum magna."),(null,"Nullam","nec enim."),(null,"ultrices","faucibus id, libero. Donec"),(null,"sollicitudin","egestas. Fusce"),(null,"libero dui","mi eleifend egestas. Sed pharetra, felis"),(null,"auctor","metus. In nec orci. Donec nibh. Quisque nonummy ipsum non"),(null,"est. Nunc","dictum ultricies ligula."),(null,"aliquet","Vestibulum ante ipsum primis in faucibus orci");
INSERT INTO `ville` (`ID_ville`,`nom_ville`,`description`) VALUES (null,"nec","urna et arcu imperdiet ullamcorper. Duis at lacus."),(null,"eu","Cras pellentesque. Sed"),(null,"mauris","rutrum magna. Cras convallis convallis dolor. Quisque tincidunt"),(null,"Nam","purus mauris a nunc. In at pede. Cras vulputate"),(null,"magnis","ligula. Aenean euismod mauris eu elit. Nulla facilisi."),(null,"aliquet magna","scelerisque neque sed"),(null,"eu nibh","rhoncus id, mollis nec, cursus a, enim. Suspendisse"),(null,"consequat","vitae, posuere at, velit. Cras lorem"),(null,"sem","parturient montes, nascetur ridiculus mus."),(null,"in, tempus","placerat eget, venenatis a, magna. Lorem ipsum dolor sit");
INSERT INTO `ville` (`ID_ville`,`nom_ville`,`description`) VALUES (null,"Proin eget","volutpat nunc sit amet metus. Aliquam erat volutpat. Nulla facilisis."),(null,"libero","urna et"),(null,"nunc est,","pellentesque, tellus sem"),(null,"leo.","ultrices posuere cubilia Curae Donec tincidunt. Donec vitae erat vel"),(null,"diam lorem,","urna."),(null,"est, mollis","Aliquam ornare, libero at auctor ullamcorper, nisl arcu iaculis enim,"),(null,"dui quis","amet nulla. Donec non justo. Proin non"),(null,"mi","Ut tincidunt vehicula risus. Nulla eget metus eu erat semper"),(null,"dictum","sed, est. Nunc laoreet lectus quis massa. Mauris vestibulum,"),(null,"sed","viverra. Donec tempus,");
INSERT INTO `ville` (`ID_ville`,`nom_ville`,`description`) VALUES (null,"est","posuere, enim nisl elementum purus, accumsan interdum libero"),(null,"sit","ut, pellentesque eget, dictum placerat,"),(null,"euismod","sed pede nec ante blandit viverra."),(null,"nonummy ipsum","placerat, orci lacus"),(null,"metus. Aliquam","amet nulla. Donec non"),(null,"velit justo","malesuada augue ut lacus. Nulla"),(null,"rhoncus.","ad litora torquent"),(null,"vel arcu","ut nisi a odio semper cursus. Integer mollis."),(null,"elit,","Vivamus nisi. Mauris nulla. Integer urna. Vivamus molestie dapibus"),(null,"dolor","iaculis enim, sit");
INSERT INTO `ville` (`ID_ville`,`nom_ville`,`description`) VALUES (null,"diam. Duis","vitae diam. Proin dolor. Nulla semper tellus"),(null,"velit eget","gravida. Praesent eu nulla at sem"),(null,"convallis","turpis egestas. Aliquam fringilla"),(null,"eget","sit amet"),(null,"tincidunt.","mi. Duis risus odio, auctor vitae, aliquet"),(null,"tincidunt,","porttitor eros nec tellus. Nunc lectus"),(null,"consequat","ligula. Donec luctus aliquet odio. Etiam ligula tortor, dictum"),(null,"molestie arcu.","enim. Nunc ut erat."),(null,"dolor.","velit"),(null,"tellus non","ultrices sit amet, risus. Donec nibh enim, gravida sit amet,");
INSERT INTO `ville` (`ID_ville`,`nom_ville`,`description`) VALUES (null,"ante","sit amet metus."),(null,"Vestibulum","et magnis dis parturient montes, nascetur ridiculus"),(null,"ornare. Fusce","cursus,"),(null,"pede,","libero at auctor ullamcorper, nisl arcu iaculis enim,"),(null,"Integer","sollicitudin a, malesuada"),(null,"nisl.","at, iaculis quis, pede. Praesent"),(null,"rutrum","pede. Nunc sed orci lobortis"),(null,"ipsum nunc","sed, hendrerit a,"),(null,"sed","in, hendrerit consectetuer,"),(null,"nunc sed","Nunc mauris");
INSERT INTO `ville` (`ID_ville`,`nom_ville`,`description`) VALUES (null,"lacus.","at, nisi. Cum sociis natoque penatibus et magnis"),(null,"nunc","Duis sit amet diam eu dolor egestas rhoncus."),(null,"viverra. Donec","lacus. Quisque imperdiet, erat nonummy ultricies"),(null,"Etiam","a ultricies adipiscing, enim mi tempor lorem, eget mollis"),(null,"at,","eros turpis non enim. Mauris quis turpis vitae purus gravida"),(null,"pede. Nunc","vehicula"),(null,"congue,","risus. Nunc ac sem ut dolor dapibus gravida."),(null,"massa.","at, iaculis quis, pede. Praesent eu dui. Cum sociis natoque"),(null,"mattis. Integer","In at pede. Cras vulputate velit"),(null,"turpis vitae","auctor");

INSERT INTO `point_interet` (`ID_pt_interet`,`nom_pt_interet`,`epoque`,`categorie`,`description_pt_interet`,`nom_architecte`,`publier`,`chemin_photo1`,`chemin_photo2`,`chemin_photo3`,`ID_ville`) VALUES (null,"eu nulla","tincidunt pede","facilisis.","sit amet,","Orson","1","rutrum non,","erat. Etiam","Quisque fringilla",8),(null,"Etiam","cursus","justo","In ornare sagittis","Dorian","1","et arcu","ipsum.","nisi dictum",22),(null,"ut ipsum","vel","quis","amet, consectetuer","Mason","1","volutpat","Nullam velit","montes, nascetur",12),(null,"blandit viverra.","massa. Mauris","velit","odio. Nam interdum enim non nisi. Aenean eget","Garrison","1","libero.","natoque penatibus","Etiam ligula",3),(null,"mauris a","nec","risus.","Sed nulla ante, iaculis nec, eleifend non, dapibus","Nasim","0","Sed nulla","nisl arcu","pede sagittis",1),(null,"Quisque","mattis","Cras","mi fringilla mi lacinia mattis. Integer eu","Valentine","1","metus. Aliquam","posuere","dignissim magna",17),(null,"libero","Aenean","in","magna. Cras convallis convallis dolor. Quisque tincidunt pede","Omar","0","erat vitae","pulvinar","ac",1),(null,"molestie tortor","varius","Etiam","dui, semper et, lacinia vitae, sodales at, velit. Pellentesque","Jonah","0","porttitor tellus","tristique","metus. In",3),(null,"Phasellus elit","semper pretium","non,","molestie. Sed","Dylan","0","pede ac","dapibus","id,",16),(null,"gravida nunc","Cras","arcu","pede sagittis augue,","Kevin","1","iaculis,","dolor","lectus",3);
INSERT INTO `point_interet` (`ID_pt_interet`,`nom_pt_interet`,`epoque`,`categorie`,`description_pt_interet`,`nom_architecte`,`publier`,`chemin_photo1`,`chemin_photo2`,`chemin_photo3`,`ID_ville`) VALUES (null,"dignissim.","accumsan","Curae","pellentesque massa lobortis","Blake","1","eu","ornare. Fusce","adipiscing fringilla,",8),(null,"posuere","velit.","penatibus","ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing ligula.","Noah","0","ac libero","venenatis","facilisis facilisis,",24),(null,"non, vestibulum","euismod","Aliquam","pellentesque eget, dictum placerat, augue. Sed molestie.","Travis","1","mi","urna.","sociis natoque",24),(null,"egestas ligula.","consectetuer","et","neque tellus, imperdiet non, vestibulum nec,","Jordan","0","ante.","leo. Morbi","velit.",5),(null,"ligula elit,","arcu. Sed","sodales","sed dolor. Fusce mi lorem, vehicula","Dorian","1","fringilla est.","arcu","nec",14),(null,"sed","sed dolor.","ultrices","molestie pharetra nibh. Aliquam ornare, libero at auctor ullamcorper,","Clayton","0","nulla.","lobortis","Sed pharetra,",2),(null,"id","Nam","Etiam","arcu. Vestibulum ante ipsum primis in faucibus orci","Maxwell","0","tincidunt pede","ridiculus","neque non",9),(null,"diam vel","aliquet","nonummy","volutpat ornare, facilisis eget, ipsum. Donec sollicitudin","Nash","0","nulla. Cras","a ultricies","morbi",1),(null,"ipsum.","egestas blandit.","et,","sem,","Octavius","1","erat,","orci","mi eleifend",18),(null,"semper pretium","at,","mi,","ut odio vel est tempor bibendum. Donec","Vernon","0","Praesent","lobortis. Class","augue. Sed",15);
INSERT INTO `point_interet` (`ID_pt_interet`,`nom_pt_interet`,`epoque`,`categorie`,`description_pt_interet`,`nom_architecte`,`publier`,`chemin_photo1`,`chemin_photo2`,`chemin_photo3`,`ID_ville`) VALUES (null,"imperdiet ullamcorper.","interdum.","Etiam","mi lorem, vehicula et, rutrum eu,","Perry","0","ante dictum","ornare, lectus","nibh.",22),(null,"pharetra ut,","risus.","ac","ut cursus luctus, ipsum leo elementum sem, vitae aliquam","Lamar","1","auctor quis,","ipsum cursus","nec, cursus",20),(null,"Fusce","vel, convallis","auctor,","Suspendisse ac metus vitae velit egestas lacinia. Sed","Lev","0","lorem","In lorem.","ante ipsum",2),(null,"commodo","interdum. Nunc","elit,","dolor. Quisque tincidunt pede ac urna. Ut tincidunt vehicula risus.","Gavin","0","urna.","molestie","sem",24),(null,"dapibus","tincidunt vehicula","et,","Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna","Ryan","0","eget,","Ut","Morbi non",16),(null,"Vivamus","blandit","urna.","et, euismod et, commodo at, libero. Morbi accumsan laoreet ipsum.","Aristotle","1","auctor vitae,","feugiat.","sollicitudin adipiscing",24),(null,"porttitor scelerisque","mattis ornare,","mus.","consectetuer adipiscing","Ivan","1","dictum ultricies","massa rutrum","pede blandit",14),(null,"magna nec","Curae","mauris","Fusce aliquam, enim nec tempus scelerisque, lorem ipsum sodales purus,","Tarik","1","mauris sagittis","mollis","eleifend non,",5),(null,"aliquet.","et,","volutpat","aliquet molestie tellus. Aenean egestas hendrerit neque. In","Dexter","1","Nunc","Etiam","morbi",8),(null,"mus. Proin","sed, sapien.","ultrices.","sollicitudin commodo ipsum.","Michael","1","In nec","quis, tristique","arcu. Sed",15);
INSERT INTO `point_interet` (`ID_pt_interet`,`nom_pt_interet`,`epoque`,`categorie`,`description_pt_interet`,`nom_architecte`,`publier`,`chemin_photo1`,`chemin_photo2`,`chemin_photo3`,`ID_ville`) VALUES (null,"mi.","elementum purus,","gravida","nulla. Donec non justo. Proin non massa non ante bibendum","Colby","0","lectus, a","dignissim","ultrices, mauris",15),(null,"nec,","Fusce mollis.","dis","dictum mi, ac mattis velit justo nec","Camden","1","ornare, libero","sapien.","dictum sapien.",2),(null,"Cras pellentesque.","Aenean gravida","rhoncus.","condimentum. Donec at arcu. Vestibulum ante ipsum primis","Zane","0","Cum","bibendum","eu",16),(null,"est.","auctor ullamcorper,","Maecenas","molestie tortor nibh sit amet orci. Ut sagittis","Amir","0","ut lacus.","Integer","justo nec",12),(null,"ornare. In","est ac","Quisque","lorem, eget mollis lectus pede et","Isaiah","1","Morbi","amet ultricies","nec tempus",18),(null,"vel, venenatis","sed,","arcu.","Quisque imperdiet, erat nonummy ultricies ornare, elit elit fermentum","Wylie","0","Vivamus sit","magna sed","tellus. Nunc",22),(null,"placerat. Cras","ut lacus.","magna.","mauris id sapien. Cras dolor dolor, tempus","Asher","1","Nunc","vulputate, risus","Suspendisse commodo",16),(null,"sem. Pellentesque","Vestibulum ut","nunc,","adipiscing lacus.","Beau","1","eros.","mi lacinia","sem egestas",17),(null,"vel,","sociis","erat,","lacus. Nulla tincidunt, neque vitae semper","Robert","0","nunc est,","viverra. Donec","ultrices.",11),(null,"ridiculus mus.","placerat, augue.","ac,","amet, consectetuer adipiscing elit. Aliquam","Castor","1","eget,","Proin velit.","ac,",3);
INSERT INTO `point_interet` (`ID_pt_interet`,`nom_pt_interet`,`epoque`,`categorie`,`description_pt_interet`,`nom_architecte`,`publier`,`chemin_photo1`,`chemin_photo2`,`chemin_photo3`,`ID_ville`) VALUES (null,"dictum","Sed malesuada","eu,","cubilia Curae Phasellus","Hoyt","0","quis","malesuada","Aenean",8),(null,"auctor","elementum","feugiat.","consectetuer euismod est arcu","Samson","1","lectus quis","ut mi.","Nullam scelerisque",20),(null,"Maecenas ornare","vitae, erat.","purus.","sit amet","Thane","0","urna.","vitae nibh.","diam.",14),(null,"laoreet lectus","nulla.","dolor.","consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus","Hop","1","leo.","Cum sociis","nunc",4),(null,"Duis mi","ultrices sit","lacus.","a ultricies adipiscing, enim mi","Harlan","0","et malesuada","Nullam","erat. Sed",3),(null,"cursus vestibulum.","est, congue","ac","dapibus id, blandit at, nisi. Cum sociis natoque penatibus et","Brady","0","auctor ullamcorper,","elit sed","dui",10),(null,"est ac","eget lacus.","consectetuer","consequat purus. Maecenas libero est, congue a, aliquet","Edan","1","enim.","Suspendisse dui.","odio",6),(null,"nec quam.","Etiam","mi","ridiculus mus. Aenean eget magna. Suspendisse tristique neque venenatis lacus.","Jarrod","1","elit","eros. Proin","sollicitudin",16),(null,"posuere cubilia","lacinia","ac","fringilla mi lacinia mattis. Integer eu lacus.","Vaughan","0","inceptos","Donec","dis parturient",7),(null,"orci","quam vel","vel,","quis diam luctus lobortis. Class aptent","Ronan","0","pede. Cras","inceptos hymenaeos.","est",3);
INSERT INTO `point_interet` (`ID_pt_interet`,`nom_pt_interet`,`epoque`,`categorie`,`description_pt_interet`,`nom_architecte`,`publier`,`chemin_photo1`,`chemin_photo2`,`chemin_photo3`,`ID_ville`) VALUES (null,"et,","ut","semper","Nullam lobortis quam a","Caleb","0","egestas.","lorem, eget","ipsum. Donec",4),(null,"sit","eu eros.","erat,","Nam interdum enim non","Hoyt","0","mauris sapien,","sit amet,","lorem",6),(null,"tempus","accumsan","malesuada","porttitor interdum. Sed","Elton","0","amet lorem","egestas,","Nullam ut",25),(null,"mauris id","lectus","Fusce","sapien imperdiet ornare. In faucibus. Morbi vehicula. Pellentesque","Thomas","1","lobortis ultrices.","mauris, aliquam","Integer in",25),(null,"aliquet","tristique neque","diam","tellus eu augue porttitor interdum. Sed auctor","Benedict","1","augue eu","Sed","dictum magna.",21),(null,"Fusce","ut odio","Nunc","arcu ac orci. Ut semper pretium neque. Morbi quis urna.","Calvin","1","in magna.","sociis","congue",18),(null,"dolor dolor,","nunc sit","facilisis,","nunc. Quisque ornare tortor at risus. Nunc ac","Mason","1","convallis est,","Cras","eget",14),(null,"tempor diam","elit.","Nulla","enim. Mauris quis turpis vitae purus","Harding","1","orci. Ut","ultrices","dolor",13),(null,"nibh.","blandit at,","eu","sagittis felis. Donec tempor, est","Ralph","1","non, egestas","aliquet.","parturient montes,",18),(null,"magna.","amet","placerat,","pretium neque. Morbi quis","Ray","1","tellus. Aenean","aliquam iaculis,","blandit mattis.",3);
INSERT INTO `point_interet` (`ID_pt_interet`,`nom_pt_interet`,`epoque`,`categorie`,`description_pt_interet`,`nom_architecte`,`publier`,`chemin_photo1`,`chemin_photo2`,`chemin_photo3`,`ID_ville`) VALUES (null,"arcu iaculis","mi. Duis","orci,","ac mi eleifend egestas.","Nasim","0","Suspendisse","posuere","aliquet.",12),(null,"justo.","quis massa.","dui.","euismod in, dolor. Fusce feugiat.","Lane","1","aliquam, enim","enim.","interdum",3),(null,"vel,","cursus et,","Mauris","lectus quis massa. Mauris vestibulum,","Felix","1","elit,","euismod","viverra. Maecenas",20),(null,"vulputate dui,","Cras","lacus.","leo. Cras vehicula aliquet libero.","Raja","1","ligula. Aenean","ipsum. Suspendisse","mollis nec,",21),(null,"Sed","elit sed","Suspendisse","egestas, urna justo faucibus lectus,","Steel","0","eget varius","pharetra.","ligula. Nullam",16),(null,"vitae, orci.","turpis","eu","tortor nibh","Kato","0","Aliquam vulputate","a","a,",13),(null,"scelerisque","nec luctus","ridiculus","risus quis diam luctus","Darius","1","egestas a,","fringilla euismod","Sed eget",1),(null,"eu","suscipit,","diam","purus ac tellus. Suspendisse sed","Andrew","0","eu tellus","Etiam","commodo",1),(null,"lacus pede","risus. Donec","mollis","cursus non, egestas","Jackson","0","Nunc","Donec felis","libero",24),(null,"ut, pharetra","enim. Suspendisse","ac","vel, faucibus","Jesse","1","hendrerit","hymenaeos. Mauris","velit.",22);
INSERT INTO `point_interet` (`ID_pt_interet`,`nom_pt_interet`,`epoque`,`categorie`,`description_pt_interet`,`nom_architecte`,`publier`,`chemin_photo1`,`chemin_photo2`,`chemin_photo3`,`ID_ville`) VALUES (null,"Quisque imperdiet,","sed sem","rutrum","Integer sem elit, pharetra","Coby","0","lobortis","vestibulum. Mauris","porttitor scelerisque",4),(null,"aliquet","Phasellus ornare.","dolor","Mauris vel turpis.","Berk","0","eleifend non,","enim,","Aenean",9),(null,"quis lectus.","Ut","erat","mauris. Suspendisse aliquet molestie tellus.","Edan","0","velit.","Phasellus","accumsan laoreet",11),(null,"orci, consectetuer","placerat, orci","purus","lacus pede sagittis augue, eu tempor erat neque non","Arsenio","1","tellus sem","gravida","lacus.",23),(null,"euismod","et magnis","dictum","vel arcu eu odio tristique pharetra.","Sawyer","0","Nullam suscipit,","luctus, ipsum","eget laoreet",24),(null,"morbi tristique","Duis","quam","lectus justo eu arcu. Morbi sit amet","Amir","1","non lorem","ultrices","Mauris nulla.",1),(null,"velit. Cras","eu elit.","magna.","accumsan","Bevis","1","Curabitur sed","Suspendisse tristique","Duis",20),(null,"erat, eget","lobortis.","nec,","fermentum risus,","Len","0","nisl","ultricies","Proin",23),(null,"risus.","auctor","ac","molestie tortor nibh sit amet orci. Ut","Lucas","0","venenatis vel,","Phasellus fermentum","enim mi",7),(null,"quam, elementum","feugiat placerat","placerat","Mauris ut quam vel","Elvis","1","libero. Proin","eu","Curabitur",6);
INSERT INTO `point_interet` (`ID_pt_interet`,`nom_pt_interet`,`epoque`,`categorie`,`description_pt_interet`,`nom_architecte`,`publier`,`chemin_photo1`,`chemin_photo2`,`chemin_photo3`,`ID_ville`) VALUES (null,"Integer","elit, a","vitae","egestas hendrerit neque. In ornare sagittis felis. Donec tempor, est","Norman","0","Phasellus","sociis natoque","eros nec",9),(null,"Sed","bibendum sed,","sagittis","tellus","Alexander","0","Mauris","eget metus.","Aenean sed",7),(null,"est, vitae","interdum ligula","dui","ante. Nunc mauris sapien, cursus","Warren","0","diam eu","mollis","eu",21),(null,"et malesuada","diam lorem,","mauris","est. Nunc ullamcorper, velit in","Otto","0","sed","risus.","luctus ut,",13),(null,"ut","ac orci.","justo","Duis gravida.","Hedley","0","Nulla eget","eros","Proin",24),(null,"montes,","eu augue","mauris","sodales nisi magna sed dui.","Dexter","0","metus.","tincidunt aliquam","a purus.",23),(null,"Etiam vestibulum","nec","id,","sit","Russell","0","tincidunt. Donec","parturient","semper",24),(null,"laoreet posuere,","justo.","elementum","turpis non enim.","Nero","1","In tincidunt","Etiam gravida","in,",15),(null,"lorem, auctor","lacus. Etiam","ante.","Cras dolor dolor,","Perry","1","montes,","magna","non,",20),(null,"vitae","mi eleifend","amet","posuere cubilia Curae","Grady","1","ac","amet risus.","nunc",23);
INSERT INTO `point_interet` (`ID_pt_interet`,`nom_pt_interet`,`epoque`,`categorie`,`description_pt_interet`,`nom_architecte`,`publier`,`chemin_photo1`,`chemin_photo2`,`chemin_photo3`,`ID_ville`) VALUES (null,"rhoncus.","dignissim magna","nibh","elit elit fermentum risus, at fringilla purus mauris a","Zachery","1","erat nonummy","risus. In","placerat",9),(null,"convallis","ut nisi","libero","Donec non justo. Proin non","Neil","0","sagittis","augue malesuada","sed,",16),(null,"odio, auctor","magna","accumsan","ornare, lectus ante dictum mi,","Alexander","1","ligula","vestibulum massa","Maecenas iaculis",20),(null,"enim,","ornare. In","luctus","Duis cursus, diam at","Kuame","0","Nunc","In","convallis convallis",17),(null,"at fringilla","facilisis","eu","eleifend non,","Alden","1","ut aliquam","eu,","tincidunt,",11),(null,"dolor vitae","facilisis.","pellentesque,","augue scelerisque mollis. Phasellus","Hamilton","1","inceptos","montes, nascetur","ornare,",1),(null,"consectetuer","nec,","ante","faucibus orci luctus et ultrices posuere cubilia Curae Donec","Herrod","0","eu","velit","lectus, a",23),(null,"eu","vestibulum lorem,","mauris","Phasellus nulla. Integer vulputate, risus","Judah","0","amet ante.","placerat, augue.","est",25),(null,"Sed id","Cras","malesuada","dolor","Peter","0","Curae","eget laoreet","nulla ante,",25),(null,"Nam","vitae","Donec","Quisque libero lacus, varius et, euismod","Ferris","1","vitae erat","egestas blandit.","et",2);

INSERT INTO `utilisateur` (`ID_utilisateur`, `nom_utilisateur`, `prenom`, `pseudo`, `mot_de_passe`, `droit_acces`, `activer`) VALUES (NULL, 'Admin', 'Admin', 'Admin', 'Admin', '0', '1');
INSERT INTO `utilisateur` (`ID_utilisateur`, `nom_utilisateur`, `prenom`, `pseudo`, `mot_de_passe`, `droit_acces`, `activer`) VALUES (NULL, 'Editeur', 'Editeur', 'Editeur', 'Editeur', '1', '1');
INSERT INTO `utilisateur` (`ID_utilisateur`, `nom_utilisateur`, `prenom`, `pseudo`, `mot_de_passe`, `droit_acces`, `activer`) VALUES (NULL, 'User1', 'User1', 'User1', 'User1', '2', '1');
INSERT INTO `utilisateur` (`ID_utilisateur`, `nom_utilisateur`, `prenom`, `pseudo`, `mot_de_passe`, `droit_acces`, `activer`) VALUES (NULL, 'User2', 'User2', 'User2', 'User2', '2', '0');